# Generated by Django 4.2.3 on 2023-11-01 11:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmissiondb',
            name='file',
            field=models.FileField(upload_to=api.models.assign_submit_file_upload_path),
        ),
    ]
