# Generated by Django 4.2.3 on 2023-08-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile_pic.webp', null=True, upload_to='profilePic/'),
        ),
    ]
