# Generated by Django 4.2.3 on 2023-08-14 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiondata',
            options={'ordering': ['-created'], 'verbose_name': 'Session Data', 'verbose_name_plural': 'Session Data'},
        ),
        migrations.AlterField(
            model_name='sessionmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
