# Generated by Django 4.2.3 on 2023-07-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verfied',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='VerifiedUser',
        ),
    ]
