# Generated by Django 4.2.3 on 2023-09-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmissiondb',
            name='submitted',
        ),
        migrations.AddField(
            model_name='assignmentpostdb',
            name='submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
