# Generated by Django 4.2.3 on 2023-08-19 14:17

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sessiondata_options_alter_sessionmember_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to=api.models.get_file_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessiondata')),
            ],
            options={
                'verbose_name': 'Documents Model',
                'verbose_name_plural': 'Documents Model',
                'ordering': ['-created_at'],
            },
        ),
    ]
