# Generated by Django 4.2.3 on 2023-09-04 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sessiondata_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentPostDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessiondata')),
            ],
            options={
                'verbose_name': 'Assignments Post Model',
                'verbose_name_plural': 'Assignments Post Model',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('submitted', models.BooleanField(default=False)),
                ('submit_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assignmentpostdb')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmember')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessiondata')),
            ],
            options={
                'verbose_name': 'Assignment Submission DB',
                'verbose_name_plural': 'Assignment Submission DB',
                'ordering': ['-submit_at'],
            },
        ),
    ]
