# Generated by Django 4.2.3 on 2023-07-26 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_is_verfied_userprofile_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('details', models.CharField(blank=True, max_length=300, null=True)),
                ('token', models.CharField(max_length=5)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Data',
                'verbose_name_plural': 'Session Data',
            },
        ),
        migrations.CreateModel(
            name='SessionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=5, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessiondata')),
            ],
            options={
                'verbose_name': 'Session Member',
                'verbose_name_plural': 'Sesson Member',
            },
        ),
        migrations.CreateModel(
            name='PostDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_announcement', models.BooleanField(blank=True, default=False, null=True)),
                ('post_body', models.TextField()),
                ('has_file', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessiondata')),
            ],
            options={
                'verbose_name': 'Post Database',
                'verbose_name_plural': 'Post Database',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='CommentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.postdb')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessiondata')),
            ],
            options={
                'verbose_name': 'Comment Database',
                'verbose_name_plural': 'Comment Database',
            },
        ),
    ]
