# Generated by Django 4.2.3 on 2023-08-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_filedb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdb',
            name='has_file',
        ),
        migrations.RemoveField(
            model_name='postdb',
            name='is_announcement',
        ),
    ]
