# Generated by Django 4.2.3 on 2023-09-19 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_assignmentpostdb_submitted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMemberBlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=5)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessiondata')),
            ],
            options={
                'verbose_name': 'Session Member Blacklist',
                'verbose_name_plural': 'Session Member Blacklist',
            },
        ),
    ]
