# Generated by Django 4.2.3 on 2023-08-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_postdb_has_file_remove_postdb_is_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postdb',
            options={'ordering': ['-created'], 'verbose_name': 'Post Database', 'verbose_name_plural': 'Post Database'},
        ),
    ]
