# Generated by Django 4.2.3 on 2023-09-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sessionmemberblacklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionMemberBlackList',
            new_name='SessionMemberBlockList',
        ),
        migrations.AlterModelOptions(
            name='sessionmemberblocklist',
            options={'verbose_name': 'Session Member Blocklist', 'verbose_name_plural': 'Session Member Blocklist'},
        ),
    ]
